admin_user=User.create(name: "didi" ,email: "didi@gmail.com",password: "123456",password_confirmation: "123456",admin: true )

global_user=User.create(name: "dada" ,email: "dada@gmail.com",password: "123456",password_confirmation: "123456",admin: false )



Task.create(title: 'first_task', content: 'manger' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'second_task', content: 'dormir' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'third_task', content: 'prier' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: global_user.id)
Task.create(title: 'fourth_task', content: 'nager' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'fifth_task', content: 'marcher' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'sixth_task', content: 'chatter' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'seventh_task', content: 'aller faire du sport' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)
Task.create(title: 'eighth_task', content: 'cuisiner' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: admin_user.id)
Task.create(title: 'nineth_task', content: 'sortir' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'tenth_task', content: 'regarder' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)

Task.create(title: 'first_task', content: 'manger' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'second_task', content: 'dormir' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'third_task', content: 'prier' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: global_user.id)
Task.create(title: 'fourth_task', content: 'nager' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'fifth_task', content: 'marcher' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'sixth_task', content: 'chatter' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'seventh_task', content: 'aller faire du sport' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)
Task.create(title: 'eighth_task', content: 'cuisiner' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: admin_user.id)
Task.create(title: 'nineth_task', content: 'sortir' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'tenth_task', content: 'regarder' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)

Task.create(title: 'first_task', content: 'manger' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'second_task', content: 'dormir' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'third_task', content: 'prier' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: global_user.id)
Task.create(title: 'fourth_task', content: 'nager' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'fifth_task', content: 'marcher' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'sixth_task', content: 'chatter' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'seventh_task', content: 'aller faire du sport' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)
Task.create(title: 'eighth_task', content: 'cuisiner' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: admin_user.id)
Task.create(title: 'nineth_task', content: 'sortir' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'tenth_task', content: 'regarder' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)

Task.create(title: 'first_task', content: 'manger' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'second_task', content: 'dormir' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'third_task', content: 'prier' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: global_user.id)
Task.create(title: 'fourth_task', content: 'nager' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'fifth_task', content: 'marcher' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'sixth_task', content: 'chatter' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'seventh_task', content: 'aller faire du sport' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)
Task.create(title: 'eighth_task', content: 'cuisiner' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: admin_user.id)
Task.create(title: 'nineth_task', content: 'sortir' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'tenth_task', content: 'regarder' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)

Task.create(title: 'first_task', content: 'manger' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'second_task', content: 'dormir' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'third_task', content: 'prier' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: global_user.id)
Task.create(title: 'fourth_task', content: 'nager' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: global_user.id)
Task.create(title: 'fifth_task', content: 'marcher' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: global_user.id)
Task.create(title: 'sixth_task', content: 'chatter' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'seventh_task', content: 'aller faire du sport' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)
Task.create(title: 'eighth_task', content: 'cuisiner' , deadline_on: '2025-02-17', priority: 'Elevee', status: 'Démarré',user_id: admin_user.id)
Task.create(title: 'nineth_task', content: 'sortir' , deadline_on: '2025-02-16', priority: 'Faible', status: 'Terminé',user_id: admin_user.id)
Task.create(title: 'tenth_task', content: 'regarder' , deadline_on: '2025-02-18', priority: 'Moyenne', status: 'Non_démarré',user_id: admin_user.id)

